display_name: Groups
icon: installer/icon.png
summary: The one with the assignments.
group: Applications/Education
vendor: JupiterBrain
packager: JupiterBrain
url: https://github.com/JupiterBrain/groups-app

buildarch: amd64

license: none

generic_name: Algorithm

categories:
  - Education
  - Utility

startup_notify: false