display_name: Groups
package_name: groups-app

maintainer:
  name: JupiterBrain

priority: optional

section: x11

installed_size: 23000

essential: false

icon: installer/icon.png

keywords:

generic_name: Algorithm

categories:
  - Education
  - Utility

startup_notify: false